version: '3'

services:
  mariadb:
    image: mariadb:latest
    container_name: kamailio-mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=kamailio
      - MYSQL_USER=kamailio
      - MYSQL_PASSWORD=kamailiorw
      - TZ=Asia/Seoul
    volumes:
      - ./mariadb:/var/lib/mysql
      - ./config/mariadb:/etc/mysql/conf.d
      - ./config/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - kamailio-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "kamailio", "-pkamailiorw"]
      interval: 5s
      timeout: 5s
      retries: 5

  kamailio:
    image: ghcr.io/kamailio/kamailio:latest
    container_name: kamailio-sip
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "5061:5061/tcp"
    volumes:
      - ./config/kamailio:/etc/kamailio
    environment:
      - TZ=Asia/Seoul
      - SIP_DOMAIN=sip.example.com
      - DBENGINE=MYSQL
      - DBHOST=mariadb
      - DBPORT=3306
      - DBNAME=kamailio
      - DBRWUSER=kamailio
      - DBRWPW=kamailiorw
    networks:
      - kamailio-net
    command: >
      bash -c "
        echo 'Waiting for MariaDB to be ready...' &&
        sleep 10 &&
        kamdbctl create &&
        touch /etc/kamailio/dispatcher.list &&
        chmod 644 /etc/kamailio/dispatcher.list &&
        cp -f /etc/kamailio/dispatcher.list /etc/kamailio/dispatcher.list.bak &&
        kamailio -DD -E
      "

networks:
  kamailio-net:
    driver: bridge
